FROM php:8.2-fpm

# マルチステージビルドを利用してのcomposerとphp-extension-installerコマンドのインストール
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
  curl \
  git \
  unzip \
  tar \
  nano \
  poppler-utils \
  tesseract-ocr \
  tesseract-ocr-jpn \
  libmagickwand-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# 必要なPHP拡張のインストール
RUN install-php-extensions pdo_mysql gd xdebug imagick

# nodeのバージョンを指定してインストール（現在は18がStableなのでそれをインストール）
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -  \
  && apt-get update && apt-get install -y \
  nodejs \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && npm install -g npm