version: '3'
services:
  web:
    build: ./docker/web
    platform: linux/x86_64
    ports:
      - 8000:80
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    depends_on:
      - app
  app:
    build: ./docker/app
    platform: linux/x86_64
    volumes:
      - ./docker/app/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    build: ./docker/db
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - fullstack-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db2
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  fullstack-db-volume: